version: "3.9"

networks:
  laravel-network:
    driver: bridge
    name: laravel-network

volumes:
  mysql-data:
    name: laravel_mysql-data
  redis-data:
    name: laravel_redis-data

services:
 
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    command: ["php-fpm"]
    volumes:
        - ./:/var/www
        - ./docker/php/startup.sh:/usr/local/bin/startup.sh
    depends_on:
        - redis
    networks:
        - laravel-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
        - "80:80"
    volumes:
        - ./:/var/www
        - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel-network

  mysql:
    build:
      context: .
      dockerfile:
        ./docker/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:cached
      - ./docker/mysql/custom-entrypoint.sh:/usr/local/bin/custom-entrypoint.sh:cached
      - mysql-data:/var/lib/mysql:delegated
    entrypoint: [ "/usr/local/bin/custom-entrypoint.sh" ]
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel-network
    cap_add:
      - SYS_NICE

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  redis:
    image: redis:latest
    platform: linux/amd64
    command: ["redis-server", "--appendonly", "yes"]
    ports:
        - "6379:6379"
    volumes:
        - redis-data:/data
    networks:
        - laravel-network

  npm:
    image: node:20.0
    volumes:
      - ./:/var/www:delegated
    working_dir: /var/www
    tty: true
    entrypoint: [ 'bash' ]
    networks:
      - laravel-network

  smtp:
    platform: linux/x86_64
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - "8003:1025"
      - "8100:8025"
    networks:
      - laravel-network
